# Generated by Django 4.1.3 on 2022-11-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENTREGABLE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='diadenacimiento',
            field=models.DateField(null=True),
        ),
    ]
